config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "events#index"
  get "events/login" => "events#login"
  post "events/verify" => "events#verify"
  get "boss/logout" => "boss#logout"

  resources :events,:boss
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/boss_controller.rb
class BossController < ApplicationController

	before_action :check_root

	def check_root
		if session[:verify] != "root"
			redirect_to events_path
		end 
	end

	def index
		@bb = Board.all
	end

	def show
		@bb = Board.find(params[:id])
	end

	def new
		@bb = Board.new
	end

	def create
		@bb = Board.new(bb_params)
		@bb.save

		redirect_to boss_index_path
	end

	def edit
		@bb = Board.find(params[:id])
	end

	def update
		@bb = Board.find(params[:id])
		@bb.update(bb_params)

		redirect_to boss_path(@bb)
	end

	def destroy
		@bb = Board.find(params[:id])
		@bb.destroy
		redirect_to boss_index_path
	end

	def logout
		session[:verify]=nil
		redirect_to events_path
	end

	def bb_params
		params.require(:board).permit(:title, :content, :date)
	end
end

app/controllers/events_controller.rb
require 'digest/md5'

class EventsController < ApplicationController

	def index
		@bb = Board.where(["date <= ?", Time.now.strftime("%Y-%m-%d")] )
	end

	def show
		@bb = Board.find(params[:id])
	end

	def login
		if session[:verify] != "root"
			@user = User.new
		else
			redirect_to boss_index_path
		end
	end

	def verify
		if user_params[:user] != "root" || Digest::MD5.hexdigest(user_params[:password]) != "63a9f0ea7bb98050796b649e85481845" 
			flash[:error]="Login unsuccessful."
			redirect_to events_login_path
		else
			session[:verify]="root"
			redirect_to boss_index_path
		end 
	end

	def user_params
		params.require(:user).permit(:user, :password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boss_helper.rb
module BossHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/boss/edit.html.erb
<div class="jumbotron" id="head">
	<div class="container">
		<h1>Root Edit</h1>
	</div>
</div>

<div id="body">
	<div class="container">
		<%= form_for @bb , :url => boss_path(@bb),:method => :patch do |f| %>
			<%= f.label :title , "Title" %>
			<%= f.text_field :title %>
			<br><br>
			<%= f.label :content , "Content" %>
			<%= f.text_area :content %>
			<br><br>
			<%= f.label :date , "Date" %>
			<%= f.date_select :date %>
			<br><br>
			<%= f.submit "Update",:class => "btn btn-success" %>
		<% end %>

		<%= link_to "<button class='btn btn-warning'>Back to Index</button>".html_safe, boss_index_path  %>
	</div>
</div>

app/views/boss/index.html.erb
<div class="jumbotron" id="head">
	<div class="container">
		<h1>Root</h1>
	</div>
</div>

<div id="tool">
	<div class="container">
		<h3>Toolbar</h3>
		<%= link_to "<button class='btn btn-primary'>New</button>".html_safe, new_boss_path %>
		<%= link_to "<button class='btn btn-danger'>Logout</button>".html_safe, boss_logout_path %>
	</div>
	<br>
</div>
<div id="body">
	<div class="container">
		<table class="t table table-striped table-bordered">
		<tr>
			<th>Title</th>
			<th>Date</th>
			<th>Action</th>
		</tr>
			<% @bb.each do |b|  %>
				<tr>
					<td><%= b.title %></td>
					<td><%= b.date %></td>
					<td>
						<%= link_to "<button class='btn btn-info'>Show</button>".html_safe, boss_path(b) %>
						<%= link_to "<button class='btn btn-info'>Edit</button>".html_safe, edit_boss_path(b) %>
						<%= link_to "<button class='btn btn-info'>Delete</button>".html_safe, boss_path(b),:method => :delete %>
				</tr>
			<% end %>
		</table>
	</div>
</div>

app/views/boss/new.html.erb
<div class="jumbotron" id="head">
	<div class="container">
		<h1>Root New</h1>
	</div>
</div>

<div id="body">
	<div class="container">
		<%= form_for @bb , :url => boss_index_path do |f| %>
			<%= f.label :title , "Title" %>
			<%= f.text_field :title %>
			<br><br>
			<%= f.label :content , "Content" %>
			<%= f.text_area :content %>
			<br><br>
			<%= f.label :date , "Date" %>
			<%= f.date_select :date %>
			<br><br>
			<%= f.submit "New",:class => "btn btn-success" %>
		<% end %>

		<%= link_to "<button class='btn btn-warning'>Back to Index</button>".html_safe, boss_index_path %>
	</div>
</div>

app/views/boss/show.html.erb
<div class="jumbotron" id="head">
	<div class="container">
		<h1>Root Content</h1>
	</div>
</div>
<div id="body">
	<div class="container">
		<table class="t table table-striped table-bordered">
		<tr>
			<th>Title</th>
			<th>Content</th>
			<th>Date</th>
			<th>Action</th>
		</tr>
			<tr>
				<td><%= @bb.title %></td>
				<td><%= @bb.content %></td>
				<td><%= @bb.date %></td>
				<td><button class="btn btn-info"><%= link_to "Back to index", boss_index_path %></button></td>
			</tr>
		</table>
	</div>
</div>

app/views/events/index.html.erb
<div class="jumbotron" id="head">
	<div class="container">
		<h1>User</h1>
	</div>
</div>
<div id="body">
	<div class="container">
		<table class="t table table-striped table-bordered">
		<tr>
			<th>Title</th>
			<th>Date</th>
			<th>Action</th>
		</tr>
		<% @bb.each do |b|  %>
			<tr>
				<td><%= b.title %></td>
				<td><%= b.date %></td>
				<td><%= link_to "<button class='btn btn-info'>Show</button>".html_safe, event_path(b) %></td>
			</tr>
		<% end %>
		</table>
		<%= link_to "<button class='btn btn-primary'>Login</button>".html_safe, events_login_path %>
	</div>
</div>

app/views/events/login.html.erb
<div class="jumbotron" id="head">
	<div class="container">
		<h1>Login</h1>
	</div>
</div>

<div id="body">
	<div class="container">
		<%= form_for @user , :url => events_verify_path do |f| %>
			<%= f.label :user , "User" %>
			<%= f.text_field :user %>
			<br><br>
			<%= f.label :password , "Password" %>
			<%= f.password_field :password %>
			<br><br>
			<div id="error"><%= flash[:error] %></div>
			<br>
			<%= f.submit "Login",:class => "btn btn-success" %>
		<% end %>

		<%= link_to "<button class='btn btn-warning'>Back to Index</button>".html_safe, boss_index_path %>
	</div>
</div>

app/views/events/show.html.erb
<div class="jumbotron" id="head">
	<div class="container">
		<h1>User Content</h1>
	</div>
</div>
<div id="body">
	<div class="container">
		<table class="t table table-striped table-bordered">
		<tr>
			<th>Title</th>
			<th>Content</th>
			<th>Date</th>
			<th>Action</th>
		</tr>
			<tr>
				<td><%= @bb.title %></td>
				<td><%= @bb.content %></td>
				<td><%= @bb.date %></td>
				<td><%= link_to "<button class='btn btn-info'>Back</button>".html_safe, events_path %></td>
			</tr>
		</table>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>N+</title>
    <%= csrf_meta_tags %>

	<link rel='stylesheet prefetch' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css'>
	<link rel='stylesheet prefetch' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css'>
	<script src='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js'></script>
	
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>